# Note 1: 가독성 개선 및 코드 간략화를 위함
# Note 2: Xcode 에디터 특성상 의미 없음
# Note 3: VC 구조상 지킬 수 없음
# Note 4: API 관련 Data class와 JSI 설계를 위함

disabled_rules:
  - conditional_binding_cascade # 조건절 줄 바꿈 허용 (Note 1)
  - file_length # 파일 길이 제한 없음 (Note 3)
  - force_cast # 강제 cast 허용 (Note 1)
  - force_try # 강제 try 허용 (Note 1)
  - function_body_length # 함수 구현부 길이 제한 없음 (Note 1)
  - function_parameter_count # 함수 파라메터 갯수 제한 없음 (Note 4)
  - line_length # 행 길이 제한 없음 (Note 2)
  - todo
  - trailing_whitespace # 구문 줄 바꿈 허용 (Note 1)
  - type_body_length # 타입 선언부 길이 제한 없음 (Note 3)
  - variable_name # 변수명 길이 제한 없음 (Note 4)
  - vertical_whitespace # 수직 여백 허용 (Note 1)

excluded:
  - Pods
